"""Cross-validated evaluation. GroupKFold by drillhole is THE result;
a single deliberate random-KFold run quantifies the spatial-leakage gap.

Run: ``python -m lithoclass.evaluate`` → ``reports/results.md``
"""

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, clone
from sklearn.metrics import balanced_accuracy_score, f1_score
from sklearn.model_selection import GroupKFold, KFold

from lithoclass.make_clean import CLEAN_PATH, ELEMENTS
from lithoclass.model import SEED, logistic_baseline, majority_baseline, random_forest
from lithoclass.transform import build_features

RESULTS_PATH = Path("reports/results.md")
N_SPLITS = 5

RF_GRID = [
    {"n_estimators": n, "max_depth": d} for n in (200, 500) for d in (None, 10, 20)
]


def evaluate_cv(
    model: BaseEstimator,
    x: pd.DataFrame,
    y: pd.Series,
    groups: pd.Series | None = None,
) -> dict:
    """Fit/predict across folds; return metrics on pooled out-of-fold predictions.

    ``groups`` present → GroupKFold (no sample's hole appears in both train
    and test). ``groups=None`` → shuffled KFold: the deliberate leakage run.
    """
    if groups is not None:
        splitter = GroupKFold(n_splits=N_SPLITS)
        splits = splitter.split(x, y, groups)
    else:
        splitter = KFold(n_splits=N_SPLITS, shuffle=True, random_state=SEED)
        splits = splitter.split(x, y)

    oof_pred = pd.Series(index=y.index, dtype="str")
    fold_f1: list[float] = []
    for train_idx, test_idx in splits:
        fitted = clone(model).fit(x.iloc[train_idx], y.iloc[train_idx])
        pred = fitted.predict(x.iloc[test_idx])
        oof_pred.iloc[test_idx] = pred
        fold_f1.append(f1_score(y.iloc[test_idx], pred, average="macro"))

    per_class = f1_score(y, oof_pred, average=None, labels=sorted(y.unique()))
    return {
        "macro_f1": f1_score(y, oof_pred, average="macro"),
        "balanced_accuracy": balanced_accuracy_score(y, oof_pred),
        "fold_f1_std": float(np.std(fold_f1)),
        "per_class_f1": pd.Series(per_class, index=sorted(y.unique())),
        "oof_pred": oof_pred,
    }


def tune_rf(
    x: pd.DataFrame, y: pd.Series, groups: pd.Series, grid: list[dict] | None = None
) -> tuple[dict, pd.DataFrame]:
    """Small grid over the grouped CV; returns (best params, results table)."""
    rows = []
    for params in grid or RF_GRID:
        res = evaluate_cv(random_forest(**params), x, y, groups)
        rows.append({**params, "macro_f1": res["macro_f1"]})
    table = pd.DataFrame(rows).sort_values("macro_f1", ascending=False)
    best = table.iloc[0][["n_estimators", "max_depth"]].to_dict()
    best["n_estimators"] = int(best["n_estimators"])
    if pd.notna(best["max_depth"]):
        best["max_depth"] = int(best["max_depth"])
    else:
        best["max_depth"] = None
    return best, table


def _fmt_pct(v: float) -> str:
    return f"{v:.3f}"


def write_results(results: dict[str, dict], tuning: pd.DataFrame, path: Path) -> None:
    """Write reports/results.md from the evaluation runs."""
    lines = [
        "# Results — Phase 3 models and validation",
        "",
        f"Generated by `python -m lithoclass.evaluate` (seed {SEED}, "
        f"{N_SPLITS}-fold CV, pooled out-of-fold metrics).",
        "Grouped CV = GroupKFold by drillhole — **the honest evaluation**. "
        "The random-KFold row exists only to quantify spatial leakage.",
        "",
        "| model | features | CV | macro-F1 | balanced acc. | fold F1 σ |",
        "|---|---|---|---|---|---|",
    ]
    for name, res in results.items():
        model, feats, cv = name.split(" | ")
        lines.append(
            f"| {model} | {feats} | {cv} | {_fmt_pct(res['macro_f1'])} | "
            f"{_fmt_pct(res['balanced_accuracy'])} | {res['fold_f1_std']:.3f} |"
        )

    main = results["RandomForest (tuned) | CLR | grouped"]
    leak = results["RandomForest (tuned) | CLR | random (leakage demo)"]
    gap = leak["macro_f1"] - main["macro_f1"]
    lines += [
        "",
        f"**Spatial-leakage gap: {_fmt_pct(leak['macro_f1'])} (random) − "
        f"{_fmt_pct(main['macro_f1'])} (grouped) = {gap:+.3f} macro-F1.** "
        "Random splits let the model see sibling samples from the same hole "
        "during training, inflating apparent skill.",
        "",
        "## Per-class F1 — RandomForest (tuned), grouped CV",
        "",
        "| class | F1 |",
        "|---|---|",
    ]
    lines += [
        f"| {cls} | {_fmt_pct(v)} |" for cls, v in main["per_class_f1"].items()
    ]
    lines += [
        "",
        "## RF tuning grid (grouped CV macro-F1)",
        "",
        "| n_estimators | max_depth | macro-F1 |",
        "|---|---|---|",
    ]
    lines += [
        f"| {int(r.n_estimators)} | {r.max_depth if pd.notna(r.max_depth) else 'None'} "
        f"| {_fmt_pct(r.macro_f1)} |"
        for r in tuning.itertuples()
    ]
    lines += [
        "",
        "Note: the grid was selected on the same grouped folds used for "
        "reporting (light tuning per the brief); differences across the grid "
        "are small, so residual selection optimism is minor.",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    """Run all evaluations and write the results report."""
    df = pd.read_parquet(CLEAN_PATH)
    x_clr, x_log10, y, groups = build_features(df, ELEMENTS)

    best, tuning = tune_rf(x_clr, y, groups)
    print(f"best RF params (grouped CV): {best}")

    results: dict[str, dict] = {}
    results["Majority class | — | grouped"] = evaluate_cv(
        majority_baseline(), x_clr, y, groups
    )
    results["Logistic regression | CLR | grouped"] = evaluate_cv(
        logistic_baseline(), x_clr, y, groups
    )
    results["RandomForest (tuned) | CLR | grouped"] = evaluate_cv(
        random_forest(**best), x_clr, y, groups
    )
    results["RandomForest (tuned) | log10 ppm | grouped"] = evaluate_cv(
        random_forest(**best), x_log10, y, groups
    )
    results["RandomForest (tuned) | CLR | random (leakage demo)"] = evaluate_cv(
        random_forest(**best), x_clr, y, groups=None
    )

    write_results(results, tuning, RESULTS_PATH)
    for name, res in results.items():
        print(f"{name}: macro-F1 {res['macro_f1']:.3f}")
    print(f"Wrote {RESULTS_PATH}")


if __name__ == "__main__":
    main()
