"""Build ``data/processed/clean.parquet`` — the Phase 1 output.

Chains the cleaning steps on the labelled subset: censored-value parsing →
unit harmonisation → per-sample pivot (element suite F) → lithology lookup →
keep-filter → complete-case filter. Writes a class-balance report with full
exclusion accounting so every dropped sample is explained.

Run: ``python -m lithoclass.make_clean``
"""

from pathlib import Path

import pandas as pd

from lithoclass.clean import apply_lookup, parse_censored, pivot_samples, to_ppm
from lithoclass.extract import OUT_PATH as LABELLED_PATH
from lithoclass.make_lookup import LOOKUP_PATH

CLEAN_PATH = Path("data/processed/clean.parquet")
BALANCE_PATH = Path("reports/class_balance.md")

# Suite F (DECISIONS 2026-07-17): low-censoring elements, chosen over the
# strict >40%-missing rule after a complete-case trade-off review.
ELEMENTS = ["Cu", "Zn", "Pb", "Co", "Ni", "Fe", "Mn"]


def build_clean(
    long_df: pd.DataFrame, lookup: pd.DataFrame, elements: list[str]
) -> tuple[pd.DataFrame, dict]:
    """Run the full cleaning chain; return (clean table, exclusion stats)."""
    numeric, flag = parse_censored(long_df["VALUE"])
    long_df = long_df.assign(
        value_ppm=to_ppm(numeric, long_df["UNIT"]), censor_flag=flag
    )
    wide = pivot_samples(long_df, elements)
    n_pivoted = len(wide)

    merged = apply_lookup(wide, lookup)
    kept_classes = set(lookup.loc[lookup["keep"] == "Y", "lith_class"])
    kept = merged[merged["lith_class"].isin(kept_classes)]
    n_excluded_class = n_pivoted - len(kept)

    element_cols = [f"{e}_ppm" for e in elements]
    complete = kept[kept[element_cols].notna().all(axis=1)]
    n_incomplete = len(kept) - len(complete)

    stats = {
        "n_samples_labelled": n_pivoted,
        "n_excluded_class": n_excluded_class,
        "n_incomplete_suite": n_incomplete,
        "n_final": len(complete),
        "n_holes_final": complete["DRILLHOLE_NUMBER"].nunique(),
    }
    return complete.reset_index(drop=True), stats


def write_balance_report(clean: pd.DataFrame, stats: dict, out_path: Path) -> None:
    """Write the class-balance table and exclusion accounting."""
    by_class = (
        clean.groupby(["tier", "lith_class"])
        .agg(
            n_samples=("SAMPLE_NO", "size"),
            n_holes=("DRILLHOLE_NUMBER", "nunique"),
        )
        .sort_values("n_samples", ascending=False)
    )
    class_lines = ["| tier | class | samples | holes |", "|---|---|---|---|"]
    class_lines += [
        f"| {tier} | {cls} | {r.n_samples:,} | {r.n_holes:,} |"
        for (tier, cls), r in by_class.iterrows()
    ]
    class_table = "\n".join(class_lines)
    md = f"""# Class balance — clean.parquet

Generated by `python -m lithoclass.make_clean` on {pd.Timestamp.now():%Y-%m-%d}.
Element suite: {", ".join(ELEMENTS)} (suite F, see DECISIONS.md).

## Sample accounting

| step | samples |
|---|---|
| labelled drillhole samples (pivoted) | {stats["n_samples_labelled"]:,} |
| − excluded classes (keep=N in lith_lookup.csv) | −{stats["n_excluded_class"]:,} |
| − incomplete element suite (CLR needs all {len(ELEMENTS)}) | −{stats["n_incomplete_suite"]:,} |
| **final** | **{stats["n_final"]:,}** (across {stats["n_holes_final"]:,} holes) |

## Classes

{class_table}
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")


def main() -> None:
    """Build clean.parquet and the class-balance report."""
    long_df = pd.read_parquet(LABELLED_PATH)
    lookup = pd.read_csv(LOOKUP_PATH)
    clean, stats = build_clean(long_df, lookup, ELEMENTS)
    CLEAN_PATH.parent.mkdir(parents=True, exist_ok=True)
    clean.to_parquet(CLEAN_PATH, index=False)
    write_balance_report(clean, stats, BALANCE_PATH)
    print(f"Wrote {CLEAN_PATH}: {stats['n_final']:,} samples, "
          f"{stats['n_holes_final']:,} holes")
    print(f"Wrote {BALANCE_PATH}")


if __name__ == "__main__":
    main()
